package vista;

import javax.swing.table.DefaultTableModel;
import java.awt.Color;


public class Form_AvionIdaEconomy extends javax.swing.JFrame {
    
    private DefaultTableModel modeloTabla;
    private int personasTotales;

    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Form_AvionIdaEconomy.class.getName());

    /**
     * Creates new form Form_AvionIdaEconomy
     */
    public Form_AvionIdaEconomy() {
        initComponents();
    
    // Configuración inicial
    personasTotales = Form_MenuPrincipal.numeroPersonas;
    modeloTabla = (javax.swing.table.DefaultTableModel) tablaAEIda.getModel();
    modeloTabla.setRowCount(0);
    btnSiguiente.setEnabled(false);
}
    private void gestionarSeleccionAsiento(java.awt.event.ActionEvent evt) {
    // 1. Validación: Número de pasajeros
    if (util.DatosReserva.vuelosIda.size() >= Form_MenuPrincipal.numeroPersonas) {
        javax.swing.JOptionPane.showMessageDialog(this, "Ya seleccionó todos los asientos necesarios.");
        return;
    }

    // 2. Extraer el botón y su número automáticamente
    javax.swing.JButton boton = (javax.swing.JButton) evt.getSource();
    String nAsiento = boton.getText(); // Toma el texto del botón
    double precio = 450.0; 

    // 3. Estética: Pintar de verde
    boton.setBackground(java.awt.Color.GREEN);
    boton.setEnabled(false);

    // 4. Guarda en util.DatosReserva
    Object[] fila = new Object[] {
        "Pasajero " + (util.DatosReserva.vuelosIda.size() + 1),
        nAsiento,
        Form_MenuPrincipal.horaVueloIda,
        precio
    };

    util.DatosReserva.vuelosIda.add(fila);
    util.DatosReserva.total += precio;
    
    // 5. Lógica para activar el botón Siguiente
    if (util.DatosReserva.vuelosIda.size() == vista.Form_MenuPrincipal.numeroPersonas) {
        btnSiguiente.setEnabled(true); // Se activa solo cuando el cupo está lleno
        javax.swing.JOptionPane.showMessageDialog(this, "Cupo completo. Ya puede continuar.");
    }
    // 6. Actualizar tabla
    DefaultTableModel modelo = (DefaultTableModel) tablaAEIda.getModel();
    modelo.setRowCount(0); // Limpiamos la vista previa para redibujarla
    
    for (Object[] f : util.DatosReserva.vuelosIda) {
        modelo.addRow(f); // Agregamos cada asiento guardado hasta ahora
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAsiento20 = new javax.swing.JButton();
        btnAsiento12 = new javax.swing.JButton();
        btnAsiento19 = new javax.swing.JButton();
        btnAsiento15 = new javax.swing.JButton();
        btnAsiento2 = new javax.swing.JButton();
        btnAsiento3 = new javax.swing.JButton();
        btnAsiento21 = new javax.swing.JButton();
        btnAsiento17 = new javax.swing.JButton();
        btnAsiento4 = new javax.swing.JButton();
        btnAsiento18 = new javax.swing.JButton();
        btnAsiento14 = new javax.swing.JButton();
        btnAsiento16 = new javax.swing.JButton();
        btnAsiento23 = new javax.swing.JButton();
        btnAsiento7 = new javax.swing.JButton();
        btnAsiento9 = new javax.swing.JButton();
        btnAsiento22 = new javax.swing.JButton();
        btnAsiento11 = new javax.swing.JButton();
        btnAsiento24 = new javax.swing.JButton();
        btnAsiento6 = new javax.swing.JButton();
        btnAsiento1 = new javax.swing.JButton();
        btnAsiento8 = new javax.swing.JButton();
        btnAsiento13 = new javax.swing.JButton();
        btnAsiento5 = new javax.swing.JButton();
        btnAsiento10 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaAEIda = new javax.swing.JTable();
        btnRegresar = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAsiento20.setBackground(new java.awt.Color(51, 204, 255));
        btnAsiento20.setText("E20");
        btnAsiento20.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAsiento20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsiento20ActionPerformed(evt);
            }
        });
        getContentPane().add(btnAsiento20, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 440, 70, 40));

        btnAsiento12.setBackground(new java.awt.Color(51, 204, 255));
        btnAsiento12.setText("E12");
        btnAsiento12.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAsiento12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsiento12ActionPerformed(evt);
            }
        });
        getContentPane().add(btnAsiento12, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 440, 70, 40));

        btnAsiento19.setBackground(new java.awt.Color(51, 204, 255));
        btnAsiento19.setText("E19");
        btnAsiento19.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAsiento19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsiento19ActionPerformed(evt);
            }
        });
        getContentPane().add(btnAsiento19, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 390, 70, 40));

        btnAsiento15.setBackground(new java.awt.Color(51, 204, 255));
        btnAsiento15.setText("E15");
        btnAsiento15.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAsiento15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsiento15ActionPerformed(evt);
            }
        });
        getContentPane().add(btnAsiento15, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 390, 70, 40));

        btnAsiento2.setBackground(new java.awt.Color(51, 204, 255));
        btnAsiento2.setText("E2");
        btnAsiento2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAsiento2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsiento2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnAsiento2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 330, 70, 40));

        btnAsiento3.setBackground(new java.awt.Color(51, 204, 255));
        btnAsiento3.setText("E3");
        btnAsiento3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAsiento3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsiento3ActionPerformed(evt);
            }
        });
        getContentPane().add(btnAsiento3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 390, 70, 40));

        btnAsiento21.setBackground(new java.awt.Color(51, 204, 255));
        btnAsiento21.setText("E21");
        btnAsiento21.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAsiento21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsiento21ActionPerformed(evt);
            }
        });
        getContentPane().add(btnAsiento21, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 280, 70, 40));

        btnAsiento17.setBackground(new java.awt.Color(51, 204, 255));
        btnAsiento17.setText("E17");
        btnAsiento17.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAsiento17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsiento17ActionPerformed(evt);
            }
        });
        getContentPane().add(btnAsiento17, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 280, 70, 40));

        btnAsiento4.setBackground(new java.awt.Color(51, 204, 255));
        btnAsiento4.setText("E4");
        btnAsiento4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAsiento4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsiento4ActionPerformed(evt);
            }
        });
        getContentPane().add(btnAsiento4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 440, 70, 40));

        btnAsiento18.setBackground(new java.awt.Color(51, 204, 255));
        btnAsiento18.setText("E18");
        btnAsiento18.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAsiento18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsiento18ActionPerformed(evt);
            }
        });
        getContentPane().add(btnAsiento18, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 330, 70, 40));

        btnAsiento14.setBackground(new java.awt.Color(51, 204, 255));
        btnAsiento14.setText("E14");
        btnAsiento14.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAsiento14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsiento14ActionPerformed(evt);
            }
        });
        getContentPane().add(btnAsiento14, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 330, 70, 40));

        btnAsiento16.setBackground(new java.awt.Color(51, 204, 255));
        btnAsiento16.setText("E16");
        btnAsiento16.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAsiento16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsiento16ActionPerformed(evt);
            }
        });
        getContentPane().add(btnAsiento16, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 440, 70, 40));

        btnAsiento23.setBackground(new java.awt.Color(51, 204, 255));
        btnAsiento23.setText("E23");
        btnAsiento23.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAsiento23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsiento23ActionPerformed(evt);
            }
        });
        getContentPane().add(btnAsiento23, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 390, 70, 40));

        btnAsiento7.setBackground(new java.awt.Color(51, 204, 255));
        btnAsiento7.setText("E7");
        btnAsiento7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAsiento7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsiento7ActionPerformed(evt);
            }
        });
        getContentPane().add(btnAsiento7, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 390, 70, 40));

        btnAsiento9.setBackground(new java.awt.Color(51, 204, 255));
        btnAsiento9.setText("E9");
        btnAsiento9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAsiento9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsiento9ActionPerformed(evt);
            }
        });
        getContentPane().add(btnAsiento9, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 280, 70, 40));

        btnAsiento22.setBackground(new java.awt.Color(51, 204, 255));
        btnAsiento22.setText("E22");
        btnAsiento22.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAsiento22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsiento22ActionPerformed(evt);
            }
        });
        getContentPane().add(btnAsiento22, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 330, 70, 40));

        btnAsiento11.setBackground(new java.awt.Color(51, 204, 255));
        btnAsiento11.setText("E11");
        btnAsiento11.setToolTipText("");
        btnAsiento11.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAsiento11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsiento11ActionPerformed(evt);
            }
        });
        getContentPane().add(btnAsiento11, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 390, 70, 40));

        btnAsiento24.setBackground(new java.awt.Color(51, 204, 255));
        btnAsiento24.setText("E24");
        btnAsiento24.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAsiento24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsiento24ActionPerformed(evt);
            }
        });
        getContentPane().add(btnAsiento24, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 440, 70, 40));

        btnAsiento6.setBackground(new java.awt.Color(51, 204, 255));
        btnAsiento6.setText("E6");
        btnAsiento6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAsiento6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsiento6ActionPerformed(evt);
            }
        });
        getContentPane().add(btnAsiento6, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 330, 70, 40));

        btnAsiento1.setBackground(new java.awt.Color(51, 204, 255));
        btnAsiento1.setText("E1");
        btnAsiento1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAsiento1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsiento1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnAsiento1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 280, 70, 40));

        btnAsiento8.setBackground(new java.awt.Color(51, 204, 255));
        btnAsiento8.setText("E8");
        btnAsiento8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAsiento8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsiento8ActionPerformed(evt);
            }
        });
        getContentPane().add(btnAsiento8, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 440, 70, 40));

        btnAsiento13.setBackground(new java.awt.Color(51, 204, 255));
        btnAsiento13.setText("E13");
        btnAsiento13.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAsiento13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsiento13ActionPerformed(evt);
            }
        });
        getContentPane().add(btnAsiento13, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 280, 70, 40));

        btnAsiento5.setBackground(new java.awt.Color(51, 204, 255));
        btnAsiento5.setText("E5");
        btnAsiento5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAsiento5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsiento5ActionPerformed(evt);
            }
        });
        getContentPane().add(btnAsiento5, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 280, 70, 40));

        btnAsiento10.setBackground(new java.awt.Color(51, 204, 255));
        btnAsiento10.setText("E10");
        btnAsiento10.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAsiento10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsiento10ActionPerformed(evt);
            }
        });
        getContentPane().add(btnAsiento10, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 330, 70, 40));

        tablaAEIda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Numero Persona", "Numero Asiento", "Hora Vuelo", "Precio USD"
            }
        ));
        jScrollPane1.setViewportView(tablaAEIda);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 580, 580, 230));

        btnRegresar.setBackground(new java.awt.Color(255, 0, 51));
        btnRegresar.setFont(new java.awt.Font("Elephant", 0, 24)); // NOI18N
        btnRegresar.setText("REGRESAR");
        btnRegresar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 680, 230, 80));

        btnSiguiente.setBackground(new java.awt.Color(0, 255, 0));
        btnSiguiente.setFont(new java.awt.Font("Elephant", 0, 24)); // NOI18N
        btnSiguiente.setText("SIGUIENTE");
        btnSiguiente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });
        getContentPane().add(btnSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 680, 230, 80));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/VueloIdaAsientosEconomy.png"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(1230, 837));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -160, 1230, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
    // Cortamos el texto para dejar solo la fecha (los primeros 10 caracteres "dd/mm/yyyy")
    if(Form_MenuPrincipal.horaVueloIda.length() > 10){
        Form_MenuPrincipal.horaVueloIda = Form_MenuPrincipal.horaVueloIda.substring(0, 10);
    }
    // Limpia los asientos de IDA seleccionados y restar sus precios del total
    util.DatosReserva.vuelosIda.clear();
    util.DatosReserva.total = 0; // Resetea costo
    new Form_VuelosIdaEconomy().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        // Valida si se seleccionaron todos los asientos necesarios
    if (util.DatosReserva.vuelosIda.size() < vista.Form_MenuPrincipal.numeroPersonas) {
        int faltantes = vista.Form_MenuPrincipal.numeroPersonas - util.DatosReserva.vuelosIda.size();
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Aún faltan seleccionar " + faltantes + " asiento(s).", 
            "Selección incompleta", 
            javax.swing.JOptionPane.WARNING_MESSAGE);
        return; // No deja pasar a la siguiente pantalla
    }

    // Si todo está bien, avanza
    new Form_CabinaVuelta().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnAsiento1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsiento1ActionPerformed
        gestionarSeleccionAsiento(evt);
    }//GEN-LAST:event_btnAsiento1ActionPerformed

    private void btnAsiento2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsiento2ActionPerformed
        gestionarSeleccionAsiento(evt);
    }//GEN-LAST:event_btnAsiento2ActionPerformed

    private void btnAsiento3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsiento3ActionPerformed
        gestionarSeleccionAsiento(evt);
    }//GEN-LAST:event_btnAsiento3ActionPerformed

    private void btnAsiento4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsiento4ActionPerformed
        gestionarSeleccionAsiento(evt);
    }//GEN-LAST:event_btnAsiento4ActionPerformed

    private void btnAsiento5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsiento5ActionPerformed
        gestionarSeleccionAsiento(evt);
    }//GEN-LAST:event_btnAsiento5ActionPerformed

    private void btnAsiento6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsiento6ActionPerformed
        gestionarSeleccionAsiento(evt);
    }//GEN-LAST:event_btnAsiento6ActionPerformed

    private void btnAsiento7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsiento7ActionPerformed
        gestionarSeleccionAsiento(evt);
    }//GEN-LAST:event_btnAsiento7ActionPerformed

    private void btnAsiento8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsiento8ActionPerformed
        gestionarSeleccionAsiento(evt);
    }//GEN-LAST:event_btnAsiento8ActionPerformed

    private void btnAsiento9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsiento9ActionPerformed
        gestionarSeleccionAsiento(evt);
    }//GEN-LAST:event_btnAsiento9ActionPerformed

    private void btnAsiento10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsiento10ActionPerformed
        gestionarSeleccionAsiento(evt);
    }//GEN-LAST:event_btnAsiento10ActionPerformed

    private void btnAsiento11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsiento11ActionPerformed
        gestionarSeleccionAsiento(evt);
    }//GEN-LAST:event_btnAsiento11ActionPerformed

    private void btnAsiento12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsiento12ActionPerformed
        gestionarSeleccionAsiento(evt);
    }//GEN-LAST:event_btnAsiento12ActionPerformed

    private void btnAsiento13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsiento13ActionPerformed
        gestionarSeleccionAsiento(evt);
    }//GEN-LAST:event_btnAsiento13ActionPerformed

    private void btnAsiento14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsiento14ActionPerformed
        gestionarSeleccionAsiento(evt);
    }//GEN-LAST:event_btnAsiento14ActionPerformed

    private void btnAsiento15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsiento15ActionPerformed
        gestionarSeleccionAsiento(evt);
    }//GEN-LAST:event_btnAsiento15ActionPerformed

    private void btnAsiento16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsiento16ActionPerformed
        gestionarSeleccionAsiento(evt);
    }//GEN-LAST:event_btnAsiento16ActionPerformed

    private void btnAsiento17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsiento17ActionPerformed
        gestionarSeleccionAsiento(evt);
    }//GEN-LAST:event_btnAsiento17ActionPerformed

    private void btnAsiento18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsiento18ActionPerformed
        gestionarSeleccionAsiento(evt);
    }//GEN-LAST:event_btnAsiento18ActionPerformed

    private void btnAsiento19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsiento19ActionPerformed
        gestionarSeleccionAsiento(evt);
    }//GEN-LAST:event_btnAsiento19ActionPerformed

    private void btnAsiento20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsiento20ActionPerformed
        gestionarSeleccionAsiento(evt);
    }//GEN-LAST:event_btnAsiento20ActionPerformed

    private void btnAsiento21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsiento21ActionPerformed
        gestionarSeleccionAsiento(evt);
    }//GEN-LAST:event_btnAsiento21ActionPerformed

    private void btnAsiento22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsiento22ActionPerformed
        gestionarSeleccionAsiento(evt);
    }//GEN-LAST:event_btnAsiento22ActionPerformed

    private void btnAsiento24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsiento24ActionPerformed
        gestionarSeleccionAsiento(evt);
    }//GEN-LAST:event_btnAsiento24ActionPerformed

    private void btnAsiento23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsiento23ActionPerformed
        gestionarSeleccionAsiento(evt);
    }//GEN-LAST:event_btnAsiento23ActionPerformed

    /**
     * @param args the command line arguments
     */

    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Form_AvionIdaEconomy().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsiento1;
    private javax.swing.JButton btnAsiento10;
    private javax.swing.JButton btnAsiento11;
    private javax.swing.JButton btnAsiento12;
    private javax.swing.JButton btnAsiento13;
    private javax.swing.JButton btnAsiento14;
    private javax.swing.JButton btnAsiento15;
    private javax.swing.JButton btnAsiento16;
    private javax.swing.JButton btnAsiento17;
    private javax.swing.JButton btnAsiento18;
    private javax.swing.JButton btnAsiento19;
    private javax.swing.JButton btnAsiento2;
    private javax.swing.JButton btnAsiento20;
    private javax.swing.JButton btnAsiento21;
    private javax.swing.JButton btnAsiento22;
    private javax.swing.JButton btnAsiento23;
    private javax.swing.JButton btnAsiento24;
    private javax.swing.JButton btnAsiento3;
    private javax.swing.JButton btnAsiento4;
    private javax.swing.JButton btnAsiento5;
    private javax.swing.JButton btnAsiento6;
    private javax.swing.JButton btnAsiento7;
    private javax.swing.JButton btnAsiento8;
    private javax.swing.JButton btnAsiento9;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaAEIda;
    // End of variables declaration//GEN-END:variables
}
