package vista;

import javax.swing.table.DefaultTableModel;

public class Form_AvionVueltaPremium extends javax.swing.JFrame {
    
private javax.swing.table.DefaultTableModel modeloTabla;

    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Form_AvionVueltaPremium.class.getName());

    /**
     * Creates new form Form_AvionVueltaPremium
     */
    public Form_AvionVueltaPremium() {
        initComponents();
        util.DatosReserva.vuelosRegreso.clear(); // Limpia datos previos de vuelta
        modeloTabla = (javax.swing.table.DefaultTableModel) tablaAPRegreso.getModel();
        modeloTabla.setRowCount(0); 
        btnSiguiente.setEnabled(false);
    }
    
    private void gestionarSeleccionAsiento(java.awt.event.ActionEvent evt) {
    // 1. Validar cupo
    if (util.DatosReserva.vuelosRegreso.size() >= vista.Form_MenuPrincipal.numeroPersonas) {
        javax.swing.JOptionPane.showMessageDialog(this, "Ya seleccionó todos los asientos de regreso.");
        return;
    }

    // AQUÍ ESTABA EL FALLO DEL COLOR
    javax.swing.JButton boton = (javax.swing.JButton) evt.getSource();
    boton.setBackground(java.awt.Color.GREEN); // Pinta el asiento de verde
    boton.setOpaque(true);
    boton.setEnabled(false); // Evita que se seleccione dos veces
    
    String nAsiento = boton.getText();
    double precio = 525.0; 

    // VALIDACIÓN DE LA HORA
    String horaVuelta = vista.Form_MenuPrincipal.horaVueloVuelta;
    if (horaVuelta == null || horaVuelta.isEmpty()) {
        horaVuelta = "No asignada"; // Texto por defecto si el menú falló
    }

    // 3. GUARDADO
    Object[] fila = new Object[] {
        "Pasajero " + (util.DatosReserva.vuelosRegreso.size() + 1),
        nAsiento,
        horaVuelta, // Usamos la variable validada
        precio
    };

    util.DatosReserva.vuelosRegreso.add(fila);
    util.DatosReserva.total += precio;

    // 4. Actualiza la tabla
    DefaultTableModel modelo = (DefaultTableModel) tablaAPRegreso.getModel(); 
    modelo.setRowCount(0);
    for (Object[] f : util.DatosReserva.vuelosRegreso) {
        modelo.addRow(f);
    }
    
    // 5. Activa el botón siguiente
    if (util.DatosReserva.vuelosRegreso.size() == vista.Form_MenuPrincipal.numeroPersonas) {
        btnSiguiente.setEnabled(true);
        btnSiguiente.setBackground(new java.awt.Color(0, 255, 0));
    }
}
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSiguiente = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaAPRegreso = new javax.swing.JTable();
        btnRegresar = new javax.swing.JButton();
        btnAsiento21 = new javax.swing.JButton();
        btnAsiento22 = new javax.swing.JButton();
        btnAsiento23 = new javax.swing.JButton();
        btnAsiento24 = new javax.swing.JButton();
        btnAsiento20 = new javax.swing.JButton();
        btnAsiento19 = new javax.swing.JButton();
        btnAsiento18 = new javax.swing.JButton();
        btnAsiento17 = new javax.swing.JButton();
        btnAsiento13 = new javax.swing.JButton();
        btnAsiento14 = new javax.swing.JButton();
        btnAsiento15 = new javax.swing.JButton();
        btnAsiento16 = new javax.swing.JButton();
        btnAsiento12 = new javax.swing.JButton();
        btnAsiento11 = new javax.swing.JButton();
        btnAsiento10 = new javax.swing.JButton();
        btnAsiento9 = new javax.swing.JButton();
        btnAsiento5 = new javax.swing.JButton();
        btnAsiento6 = new javax.swing.JButton();
        btnAsiento7 = new javax.swing.JButton();
        btnAsiento8 = new javax.swing.JButton();
        btnAsiento4 = new javax.swing.JButton();
        btnAsiento3 = new javax.swing.JButton();
        btnAsiento2 = new javax.swing.JButton();
        btnAsiento1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSiguiente.setBackground(new java.awt.Color(0, 255, 0));
        btnSiguiente.setFont(new java.awt.Font("Elephant", 0, 24)); // NOI18N
        btnSiguiente.setText("SIGUIENTE");
        btnSiguiente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });
        getContentPane().add(btnSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 700, 230, 80));

        tablaAPRegreso.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Numero Persona", "Numero Asiento", "Hora Vuelo", "Precio USD"
            }
        ));
        jScrollPane1.setViewportView(tablaAPRegreso);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 570, 560, 230));

        btnRegresar.setBackground(new java.awt.Color(255, 0, 51));
        btnRegresar.setFont(new java.awt.Font("Elephant", 0, 24)); // NOI18N
        btnRegresar.setText("REGRESAR");
        btnRegresar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 700, 230, 80));

        btnAsiento21.setBackground(new java.awt.Color(51, 204, 255));
        btnAsiento21.setText("A21");
        btnAsiento21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsiento21ActionPerformed(evt);
            }
        });
        getContentPane().add(btnAsiento21, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 70, 40));

        btnAsiento22.setBackground(new java.awt.Color(51, 204, 255));
        btnAsiento22.setText("A22");
        btnAsiento22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsiento22ActionPerformed(evt);
            }
        });
        getContentPane().add(btnAsiento22, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 70, 40));

        btnAsiento23.setBackground(new java.awt.Color(51, 204, 255));
        btnAsiento23.setText("A23");
        btnAsiento23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsiento23ActionPerformed(evt);
            }
        });
        getContentPane().add(btnAsiento23, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 70, 40));

        btnAsiento24.setBackground(new java.awt.Color(51, 204, 255));
        btnAsiento24.setText("A24");
        btnAsiento24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsiento24ActionPerformed(evt);
            }
        });
        getContentPane().add(btnAsiento24, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 70, 40));

        btnAsiento20.setBackground(new java.awt.Color(51, 204, 255));
        btnAsiento20.setText("A20");
        btnAsiento20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsiento20ActionPerformed(evt);
            }
        });
        getContentPane().add(btnAsiento20, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 70, 40));

        btnAsiento19.setBackground(new java.awt.Color(51, 204, 255));
        btnAsiento19.setText("A19");
        btnAsiento19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsiento19ActionPerformed(evt);
            }
        });
        getContentPane().add(btnAsiento19, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 70, 40));

        btnAsiento18.setBackground(new java.awt.Color(51, 204, 255));
        btnAsiento18.setText("A18");
        btnAsiento18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsiento18ActionPerformed(evt);
            }
        });
        getContentPane().add(btnAsiento18, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 70, 40));

        btnAsiento17.setBackground(new java.awt.Color(51, 204, 255));
        btnAsiento17.setText("A17");
        btnAsiento17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsiento17ActionPerformed(evt);
            }
        });
        getContentPane().add(btnAsiento17, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 70, 40));

        btnAsiento13.setBackground(new java.awt.Color(51, 204, 255));
        btnAsiento13.setText("A13");
        btnAsiento13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsiento13ActionPerformed(evt);
            }
        });
        getContentPane().add(btnAsiento13, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 70, 40));

        btnAsiento14.setBackground(new java.awt.Color(51, 204, 255));
        btnAsiento14.setText("A14");
        btnAsiento14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsiento14ActionPerformed(evt);
            }
        });
        getContentPane().add(btnAsiento14, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 70, 40));

        btnAsiento15.setBackground(new java.awt.Color(51, 204, 255));
        btnAsiento15.setText("A15");
        btnAsiento15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsiento15ActionPerformed(evt);
            }
        });
        getContentPane().add(btnAsiento15, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 70, 40));

        btnAsiento16.setBackground(new java.awt.Color(51, 204, 255));
        btnAsiento16.setText("A16");
        btnAsiento16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsiento16ActionPerformed(evt);
            }
        });
        getContentPane().add(btnAsiento16, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 70, 40));

        btnAsiento12.setBackground(new java.awt.Color(51, 204, 255));
        btnAsiento12.setText("A12");
        btnAsiento12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsiento12ActionPerformed(evt);
            }
        });
        getContentPane().add(btnAsiento12, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 340, 70, 40));

        btnAsiento11.setBackground(new java.awt.Color(51, 204, 255));
        btnAsiento11.setText("A11");
        btnAsiento11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsiento11ActionPerformed(evt);
            }
        });
        getContentPane().add(btnAsiento11, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, 70, 40));

        btnAsiento10.setBackground(new java.awt.Color(51, 204, 255));
        btnAsiento10.setText("A10");
        btnAsiento10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsiento10ActionPerformed(evt);
            }
        });
        getContentPane().add(btnAsiento10, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, 70, 40));

        btnAsiento9.setBackground(new java.awt.Color(51, 204, 255));
        btnAsiento9.setText("A9");
        btnAsiento9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsiento9ActionPerformed(evt);
            }
        });
        getContentPane().add(btnAsiento9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 70, 40));

        btnAsiento5.setBackground(new java.awt.Color(51, 204, 255));
        btnAsiento5.setText("A5");
        btnAsiento5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsiento5ActionPerformed(evt);
            }
        });
        getContentPane().add(btnAsiento5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, 70, 40));

        btnAsiento6.setBackground(new java.awt.Color(51, 204, 255));
        btnAsiento6.setText("A6");
        btnAsiento6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsiento6ActionPerformed(evt);
            }
        });
        getContentPane().add(btnAsiento6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, 70, 40));

        btnAsiento7.setBackground(new java.awt.Color(51, 204, 255));
        btnAsiento7.setText("A7");
        btnAsiento7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsiento7ActionPerformed(evt);
            }
        });
        getContentPane().add(btnAsiento7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, 70, 40));

        btnAsiento8.setBackground(new java.awt.Color(51, 204, 255));
        btnAsiento8.setText("A8");
        btnAsiento8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsiento8ActionPerformed(evt);
            }
        });
        getContentPane().add(btnAsiento8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, 70, 40));

        btnAsiento4.setBackground(new java.awt.Color(51, 204, 255));
        btnAsiento4.setText("A4");
        btnAsiento4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsiento4ActionPerformed(evt);
            }
        });
        getContentPane().add(btnAsiento4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 340, 70, 40));

        btnAsiento3.setBackground(new java.awt.Color(51, 204, 255));
        btnAsiento3.setText("A3");
        btnAsiento3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsiento3ActionPerformed(evt);
            }
        });
        getContentPane().add(btnAsiento3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 290, 70, 40));

        btnAsiento2.setBackground(new java.awt.Color(51, 204, 255));
        btnAsiento2.setText("A2");
        btnAsiento2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsiento2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnAsiento2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 230, 70, 40));

        btnAsiento1.setBackground(new java.awt.Color(51, 204, 255));
        btnAsiento1.setText("A1");
        btnAsiento1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsiento1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnAsiento1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 180, 70, 40));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/VueloRegresoAsientosPremium.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 836, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        new Form_DatosPagar().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
            // Cortamos el texto para dejar solo la fecha (los primeros 10 caracteres "dd/mm/yyyy")
    if(Form_MenuPrincipal.horaVueloVuelta.length() > 10){
        Form_MenuPrincipal.horaVueloVuelta = Form_MenuPrincipal.horaVueloVuelta.substring(0, 10);
    }
        util.DatosReserva.vuelosRegreso.clear(); // Limpiamos solo los de vuelta
        new Form_VuelosVueltaPremium().setVisible(true); 
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnAsiento1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsiento1ActionPerformed
        gestionarSeleccionAsiento(evt);
    }//GEN-LAST:event_btnAsiento1ActionPerformed

    private void btnAsiento2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsiento2ActionPerformed
        gestionarSeleccionAsiento(evt);
    }//GEN-LAST:event_btnAsiento2ActionPerformed

    private void btnAsiento3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsiento3ActionPerformed
        gestionarSeleccionAsiento(evt);
    }//GEN-LAST:event_btnAsiento3ActionPerformed

    private void btnAsiento4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsiento4ActionPerformed
        gestionarSeleccionAsiento(evt);
    }//GEN-LAST:event_btnAsiento4ActionPerformed

    private void btnAsiento5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsiento5ActionPerformed
        gestionarSeleccionAsiento(evt);
    }//GEN-LAST:event_btnAsiento5ActionPerformed

    private void btnAsiento6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsiento6ActionPerformed
        gestionarSeleccionAsiento(evt);
    }//GEN-LAST:event_btnAsiento6ActionPerformed

    private void btnAsiento7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsiento7ActionPerformed
        gestionarSeleccionAsiento(evt);
    }//GEN-LAST:event_btnAsiento7ActionPerformed

    private void btnAsiento8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsiento8ActionPerformed
        gestionarSeleccionAsiento(evt);
    }//GEN-LAST:event_btnAsiento8ActionPerformed

    private void btnAsiento9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsiento9ActionPerformed
        gestionarSeleccionAsiento(evt);
    }//GEN-LAST:event_btnAsiento9ActionPerformed

    private void btnAsiento10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsiento10ActionPerformed
        gestionarSeleccionAsiento(evt);
    }//GEN-LAST:event_btnAsiento10ActionPerformed

    private void btnAsiento11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsiento11ActionPerformed
        gestionarSeleccionAsiento(evt);
    }//GEN-LAST:event_btnAsiento11ActionPerformed

    private void btnAsiento12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsiento12ActionPerformed
        gestionarSeleccionAsiento(evt);
    }//GEN-LAST:event_btnAsiento12ActionPerformed

    private void btnAsiento13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsiento13ActionPerformed
        gestionarSeleccionAsiento(evt);
    }//GEN-LAST:event_btnAsiento13ActionPerformed

    private void btnAsiento14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsiento14ActionPerformed
        gestionarSeleccionAsiento(evt);
    }//GEN-LAST:event_btnAsiento14ActionPerformed

    private void btnAsiento15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsiento15ActionPerformed
        gestionarSeleccionAsiento(evt);
    }//GEN-LAST:event_btnAsiento15ActionPerformed

    private void btnAsiento16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsiento16ActionPerformed
        gestionarSeleccionAsiento(evt);
    }//GEN-LAST:event_btnAsiento16ActionPerformed

    private void btnAsiento17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsiento17ActionPerformed
        gestionarSeleccionAsiento(evt);
    }//GEN-LAST:event_btnAsiento17ActionPerformed

    private void btnAsiento18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsiento18ActionPerformed
        gestionarSeleccionAsiento(evt);
    }//GEN-LAST:event_btnAsiento18ActionPerformed

    private void btnAsiento19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsiento19ActionPerformed
        gestionarSeleccionAsiento(evt);
    }//GEN-LAST:event_btnAsiento19ActionPerformed

    private void btnAsiento20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsiento20ActionPerformed
        gestionarSeleccionAsiento(evt);
    }//GEN-LAST:event_btnAsiento20ActionPerformed

    private void btnAsiento21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsiento21ActionPerformed
        gestionarSeleccionAsiento(evt);
    }//GEN-LAST:event_btnAsiento21ActionPerformed

    private void btnAsiento22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsiento22ActionPerformed
        gestionarSeleccionAsiento(evt);
    }//GEN-LAST:event_btnAsiento22ActionPerformed

    private void btnAsiento23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsiento23ActionPerformed
        gestionarSeleccionAsiento(evt);
    }//GEN-LAST:event_btnAsiento23ActionPerformed

    private void btnAsiento24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsiento24ActionPerformed
        gestionarSeleccionAsiento(evt);
    }//GEN-LAST:event_btnAsiento24ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Form_AvionVueltaPremium().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsiento1;
    private javax.swing.JButton btnAsiento10;
    private javax.swing.JButton btnAsiento11;
    private javax.swing.JButton btnAsiento12;
    private javax.swing.JButton btnAsiento13;
    private javax.swing.JButton btnAsiento14;
    private javax.swing.JButton btnAsiento15;
    private javax.swing.JButton btnAsiento16;
    private javax.swing.JButton btnAsiento17;
    private javax.swing.JButton btnAsiento18;
    private javax.swing.JButton btnAsiento19;
    private javax.swing.JButton btnAsiento2;
    private javax.swing.JButton btnAsiento20;
    private javax.swing.JButton btnAsiento21;
    private javax.swing.JButton btnAsiento22;
    private javax.swing.JButton btnAsiento23;
    private javax.swing.JButton btnAsiento24;
    private javax.swing.JButton btnAsiento3;
    private javax.swing.JButton btnAsiento4;
    private javax.swing.JButton btnAsiento5;
    private javax.swing.JButton btnAsiento6;
    private javax.swing.JButton btnAsiento7;
    private javax.swing.JButton btnAsiento8;
    private javax.swing.JButton btnAsiento9;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaAPRegreso;
    // End of variables declaration//GEN-END:variables
}
